name: app1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^5.0.0

# Flutter launcher icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/kitabu_kpe.png'
  

flutter:
  assets:
    - assets/kitabu_kpe.png
  uses-material-design: true
